server {
    listen       80;
    server_name  localhost;


    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

        gzip on;
        gzip_disable "msie6";

        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;

        # File types to compress
        gzip_types
        application/javascript
        application/x-javascript
        application/json
        application/xml
        text/javascript
        text/plain
        text/css
        text/xml
        text/json
        font/ttf
        font/otf
        image/svg+xml;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
        }
}